// CS2 Server Full Setup — RCON + FTP config push
import net from "net";
import { Client } from "basic-ftp";
import { Readable } from "stream";

const rcon = { host: "185.194.236.142", port: 30045, pass: "FetchingJealous1" };
const ftp = { host: "de35.fsho.st", port: 21, user: "343263", pass: "tZWNVrJ4CKUz" };

// ── RCON Helper ─────────────────────────────────────────────
function sendRcon(cmd) {
  return new Promise((resolve, reject) => {
    const socket = new net.Socket();
    let authed = false, response = "";
    const timeout = setTimeout(() => { socket.destroy(); resolve(`[timeout] ${cmd}`); }, 5000);

    function sendPacket(reqId, type, payload) {
      const payloadBuf = Buffer.from(payload, "utf8");
      const size = 8 + payloadBuf.length + 2;
      const buf = Buffer.alloc(4 + size);
      buf.writeInt32LE(size, 0); buf.writeInt32LE(reqId, 4); buf.writeInt32LE(type, 8);
      payloadBuf.copy(buf, 12); buf.writeUInt8(0, 12 + payloadBuf.length); buf.writeUInt8(0, 13 + payloadBuf.length);
      socket.write(buf);
    }

    socket.connect(rcon.port, rcon.host, () => sendPacket(999, 3, rcon.pass));
    socket.on("data", (data) => {
      const buf = Buffer.isBuffer(data) ? data : Buffer.from(data);
      let off = 0;
      while (off < buf.length) {
        if (buf.length - off < 12) break;
        const size = buf.readInt32LE(off);
        if (buf.length - off < size + 4) break;
        const reqId = buf.readInt32LE(off + 4), type = buf.readInt32LE(off + 8);
        const payload = buf.toString("utf8", off + 12, off + 4 + size - 2);
        off += 4 + size;
        if (!authed) {
          if (reqId === -1) { clearTimeout(timeout); socket.destroy(); reject("Auth failed"); return; }
          if ((type === 2 || type === 0) && reqId === 999) { authed = true; sendPacket(1000, 2, cmd); }
        } else if (reqId === 1000) {
          response += payload;
          clearTimeout(timeout); socket.destroy(); resolve(response.trim());
          return;
        }
      }
    });
    socket.on("error", (err) => { clearTimeout(timeout); resolve(`[error] ${err.message}`); });
    socket.on("close", () => { clearTimeout(timeout); resolve(response.trim()); });
  });
}

async function rconBatch(commands) {
  for (const cmd of commands) {
    const res = await sendRcon(cmd);
    const display = res ? ` → ${res.substring(0, 80)}` : "";
    console.log(`  ✅ ${cmd}${display}`);
    await new Promise(r => setTimeout(r, 300)); // brief delay between commands
  }
}

// ── Tournament Server Config ────────────────────────────────
const tournamentAutoexec = `// ═══════════════════════════════════════════════════
// Janaxf 5v5 CS2 Community Tournament — Server Config
// Auto-generated by Esports-Bracket-Flow
// ═══════════════════════════════════════════════════

// ── Server Identity ──────────────────────────────────
hostname "Janaxf Community | 5v5 Turnier"
sv_password "janaxfcommunity"

// ── Anti-Cheat & Security ────────────────────────────
sv_cheats 0
sv_lan 0

// ── Team Settings ────────────────────────────────────
mp_autoteambalance 0
mp_limitteams 0
mp_teammates_are_enemies 0

// ── Match Settings ───────────────────────────────────
mp_maxrounds 24
mp_overtime_enable 1
mp_overtime_maxrounds 6
mp_overtime_halftime_pausetimer 0
mp_match_restart_delay 15
mp_match_end_restart 0

// ── Round Timers ─────────────────────────────────────
mp_roundtime 1.92
mp_roundtime_defuse 1.92
mp_roundtime_hostage 1.92
mp_freezetime 15
mp_buytime 20
mp_c4timer 40

// ── Warmup ───────────────────────────────────────────
mp_warmuptime 120
mp_warmup_pausetimer 0

// ── Knife Round (handled by MatchZy) ─────────────────
// MatchZy manages knife rounds natively

// ── Gameplay ─────────────────────────────────────────
mp_free_armor 0
mp_startmoney 800
mp_afterroundmoney 0
mp_playercashawards 1
mp_teamcashawards 1
mp_maxmoney 16000
mp_death_drop_gun 1
mp_death_drop_grenade 1
mp_death_drop_defuser 1

// ── Communication ────────────────────────────────────
sv_talk_enemy_dead 0
sv_talk_enemy_living 0
sv_deadtalk 1
sv_alltalk 0
sv_full_alltalk 0

// ── Spectator ────────────────────────────────────────
mp_forcecamera 1
sv_specnoclip 1
sv_specspeed 3
spec_replay_enable 0

// ── Performance ──────────────────────────────────────
sv_maxrate 0
sv_minrate 128000
sv_mincmdrate 128
sv_minupdaterate 128
sv_maxupdaterate 128

// ── Pause Settings ───────────────────────────────────
mp_team_timeout_max 4
mp_team_timeout_time 30

// ── Logging ──────────────────────────────────────────
log on
mp_logdetail 3

echo "═══════════════════════════════════════"
echo "  Janaxf Tournament Config loaded!"
echo "═══════════════════════════════════════"
`;

// ── MatchZy Config (config.cfg for FSH-MatchZy) ─────
const matchzyConfig = `// MatchZy Configuration — Janaxf Tournament
// Applied via FTP to cfg/MatchZy/config.cfg

matchzy_autostart_mode "1"
matchzy_minimum_ready_required "2"
matchzy_knife_enabled_default "true"
matchzy_playout_enabled_default "false"
matchzy_demo_upload_url ""
matchzy_stop_command_available "true"
matchzy_pause_on_veto "false"
matchzy_smoke_color_enabled "true"
matchzy_chat_prefix "[Janaxf Turnier]"
matchzy_admin_chat_prefix "[ADMIN]"
`;

// ── Main ────────────────────────────────────────────
async function run() {
  console.log("\n╔══════════════════════════════════════════════════╗");
  console.log("║   CS2 SERVER FULL SETUP — Janaxf Tournament      ║");
  console.log("╚══════════════════════════════════════════════════╝\n");

  // ── Step 1: Upload configs via FTP ─────────────────
  console.log("━━━ STEP 1: Upload Configs via FTP ━━━\n");
  const ftpClient = new Client();
  try {
    await ftpClient.access({
      host: ftp.host, port: ftp.port, user: ftp.user, password: ftp.pass,
      secure: true, secureOptions: { rejectUnauthorized: false },
    });
    console.log("  ✅ FTP connected\n");

    // Upload tournament autoexec
    console.log("  📤 Uploading tournament_autoexec.cfg...");
    await ftpClient.uploadFrom(
      Readable.from(Buffer.from(tournamentAutoexec, "utf8")),
      "p3611/cfg/tournament_autoexec.cfg"
    );
    console.log("  ✅ p3611/cfg/tournament_autoexec.cfg uploaded\n");

    // Backup existing MatchZy config and upload new one
    console.log("  📤 Uploading MatchZy config.cfg...");
    await ftpClient.uploadFrom(
      Readable.from(Buffer.from(matchzyConfig, "utf8")),
      "p3611/cfg/MatchZy/config.cfg"
    );
    console.log("  ✅ p3611/cfg/MatchZy/config.cfg uploaded\n");

  } catch (err) {
    console.log(`  ❌ FTP Error: ${err.message}\n`);
  } finally {
    ftpClient.close();
  }

  // ── Step 2: Apply settings via RCON ────────────────
  console.log("━━━ STEP 2: Apply Settings via RCON ━━━\n");

  console.log("  🔧 Server Identity & Security:");
  await rconBatch([
    'hostname "Janaxf Community | 5v5 Turnier"',
    'sv_password "janaxfcommunity"',
    'sv_cheats 0',
  ]);

  console.log("\n  🔧 Team & Match Settings:");
  await rconBatch([
    'mp_autoteambalance 0',
    'mp_limitteams 0',
    'mp_maxrounds 24',
    'mp_overtime_enable 1',
    'mp_overtime_maxrounds 6',
    'mp_match_restart_delay 15',
  ]);

  console.log("\n  🔧 Round Timers:");
  await rconBatch([
    'mp_roundtime 1.92',
    'mp_roundtime_defuse 1.92',
    'mp_freezetime 15',
    'mp_buytime 20',
    'mp_c4timer 40',
  ]);

  console.log("\n  🔧 Economy:");
  await rconBatch([
    'mp_free_armor 0',
    'mp_startmoney 800',
    'mp_maxmoney 16000',
    'mp_playercashawards 1',
    'mp_teamcashawards 1',
  ]);

  console.log("\n  🔧 Communication:");
  await rconBatch([
    'sv_talk_enemy_dead 0',
    'sv_talk_enemy_living 0',
    'sv_alltalk 0',
    'sv_deadtalk 1',
  ]);

  console.log("\n  🔧 Warmup & Pause:");
  await rconBatch([
    'mp_warmuptime 120',
    'mp_team_timeout_max 4',
    'mp_team_timeout_time 30',
  ]);

  // Load our tournament autoexec
  console.log("\n  🔧 Executing tournament config:");
  await rconBatch([
    'exec tournament_autoexec',
  ]);

  // ── Step 3: Verify ─────────────────────────────────
  console.log("\n━━━ STEP 3: Verify Server Status ━━━\n");
  const status = await sendRcon("status");
  console.log("  Server Status:");
  status.split("\n").slice(0, 8).forEach(l => console.log(`    ${l}`));

  const hostname = await sendRcon("hostname");
  console.log(`\n  Hostname: ${hostname}`);

  console.log("\n╔══════════════════════════════════════════════════╗");
  console.log("║   ✅ SERVER FULLY CONFIGURED!                     ║");
  console.log("║                                                   ║");
  console.log("║   Hostname:  Janaxf Community | 5v5 Turnier       ║");
  console.log("║   Password:  janaxfcommunity                      ║");
  console.log("║   RCON:      185.194.236.142:30045                ║");
  console.log("║   Overtime:  MR6 enabled                          ║");
  console.log("║   Rounds:    MR24 (12+12)                         ║");
  console.log("║   MatchZy:   Auto-start, knife rounds, chat prefix║");
  console.log("╚══════════════════════════════════════════════════╝\n");
}

run().catch(err => { console.log(`\n❌ Fatal: ${err.message}`); process.exit(1); });
